# Generated by Django 3.2.9 on 2022-01-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeksurvey', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=200),
        ),
    ]
