# Generated by Django 3.2.9 on 2022-01-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeksurvey', '0003_auto_20220104_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
