# Generated by Django 3.2.9 on 2022-01-24 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geeksurvey', '0004_profile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(verbose_name='expiry date')),
                ('completion_code', models.TextField(max_length=32)),
                ('survey_url', models.URLField()),
                ('completed', models.ManyToManyField(related_name='completed', to=settings.AUTH_USER_MODEL)),
                ('enrolled', models.ManyToManyField(related_name='enrolled', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.AddField(
            model_name='profile',
            name='level_of_education',
            field=models.CharField(choices=[('HS', 'High School or Equivalent'), ('BD', "Bachelor's Degree"), ('MD', "Master's Degree"), ('PHD', 'PhD or Equivalent')], default='HS', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('SWE', 'Software Engineer/Developer'), ('DSCI', 'Data Scientist'), ('SYSA', 'System Administrator/Analyst'), ('PRDM', 'Product Manager'), ('NWA', 'Network Administrator/Analyst'), ('DBA', 'Database Administrator/Analyst'), ('SECA', 'Security Analyst'), ('PROF', 'Professor/Instructor'), ('RSCHR', 'Researcher'), ('SWT', 'Software Tester')], default='SWE', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_exp',
            field=models.IntegerField(default=0),
        ),
    ]
