# Generated by Django 3.2.9 on 2022-01-24 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geeksurvey', '0005_auto_20220124_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='study',
            name='enrolled',
            field=models.ManyToManyField(blank=True, related_name='enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='study',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
